name: CI

on:
  push:
    branches:
      - master
      - dev_unittest # TODO:(Nickrader) added for testing; remove for PR
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'
  pull_request:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - 'docs/**'
      - 'maps/**'
      - 'CREDITS'
      - 'LICENSE'
      - '**.md'

env:
  BUILD_TYPE: Release
  BUILD_DIR: ${{github.workspace}}/build

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: cmake -B ${{env.BUILD_DIR}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2

      - name: Test
        run: ./build/bin/unit_tests

  ladder_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure
        run: |
          cmake \
            -B ${{env.BUILD_DIR}} \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DBUILD_SC2_RENDERER=OFF \
            -DBUILD_API_EXAMPLES=OFF \
            -DBUILD_API_TESTS=OFF \
            -DSC2_VERSION=4.10.0

      - name: Build
        run: cmake --build ${{env.BUILD_DIR}} --config ${{env.BUILD_TYPE}} --parallel 2

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pre-commit/action@v3.0.0
